// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIj7luegkwKZ2bdYtJkAawZwjBh3QiCtI',
    appId: '1:505357596687:web:a1389257476c65be2b4b7a',
    messagingSenderId: '505357596687',
    projectId: 'ai-life-manager-b2556',
    authDomain: 'ai-life-manager-b2556.firebaseapp.com',
    storageBucket: 'ai-life-manager-b2556.firebasestorage.app',
    measurementId: 'G-DBXDMT4F5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvUmhRsISZjgy6zuaRby5Ayk-IWWGxAfE',
    appId: '1:505357596687:android:6b88eac69d4002152b4b7a',
    messagingSenderId: '505357596687',
    projectId: 'ai-life-manager-b2556',
    storageBucket: 'ai-life-manager-b2556.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzYS74zJUqQ3ojIJ-HZ6252rlOTWVEPjE',
    appId: '1:505357596687:ios:89b9782f60a128d82b4b7a',
    messagingSenderId: '505357596687',
    projectId: 'ai-life-manager-b2556',
    storageBucket: 'ai-life-manager-b2556.firebasestorage.app',
    iosBundleId: 'com.example.bumpBondFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzYS74zJUqQ3ojIJ-HZ6252rlOTWVEPjE',
    appId: '1:505357596687:ios:89b9782f60a128d82b4b7a',
    messagingSenderId: '505357596687',
    projectId: 'ai-life-manager-b2556',
    storageBucket: 'ai-life-manager-b2556.firebasestorage.app',
    iosBundleId: 'com.example.bumpBondFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIj7luegkwKZ2bdYtJkAawZwjBh3QiCtI',
    appId: '1:505357596687:web:5116e12711e1c6582b4b7a',
    messagingSenderId: '505357596687',
    projectId: 'ai-life-manager-b2556',
    authDomain: 'ai-life-manager-b2556.firebaseapp.com',
    storageBucket: 'ai-life-manager-b2556.firebasestorage.app',
    measurementId: 'G-XCVNDBE3K5',
  );
}
